"""
Real AWS SES email sending for agent5.

Two send paths, both via the SESv2 API (boto3, already a project dependency):

  • send_otp_email(...)      — plain-text one-time-code email for authentication.
  • send_meeting_email(...)  — raw MIME email with a hand-rolled ``.ics`` calendar
                               invite attached, used when a visitor wants to talk to a
                               human (the scheduling sub-agent).

Sender identity + region come from the effective config (agent.config.yaml defaults ⊕
state/config/setup.yaml). SES must be configured in the AWS account (verified sender,
sandbox exit) for delivery to succeed — but a missing sender or an SES error NEVER
crashes the agent: every function returns a structured ``{"sent": bool, ...}`` result so
the chat/voice layer can report the outcome gracefully.

No new dependencies: ``.ics`` is generated by hand and the MIME message uses the stdlib
``email`` package.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from commons.logger import get_logger

logger = get_logger(__name__)


def _ses_settings() -> tuple[str, str]:
    """Return (sender, region) from the effective config, with safe fallbacks."""
    try:
        from agents.agent5.apis.service import effective_config
        cfg = effective_config()
        defaults = cfg.get("defaults") or {}
        sender = str(defaults.get("ses_sender") or "").strip()
    except Exception:  # pragma: no cover - defensive
        sender = ""
    from agents.agent5.agentic.model import resolve_region
    return sender, resolve_region()


def _ses_client(region: str):
    import boto3  # imported lazily so import errors surface as a structured result
    return boto3.client("sesv2", region_name=region)


# ── OTP email ───────────────────────────────────────────────────────────────

def send_otp_email(to_address: str, code: str, ttl_minutes: int) -> dict:
    """Send a one-time verification code via SES. Returns {sent, message_id|error}."""
    sender, region = _ses_settings()
    if not sender:
        return {"sent": False, "error": "no_ses_sender_configured"}

    subject = "Your Trianz Concierge verification code"
    body_text = (
        f"Your Trianz Concierge verification code is: {code}\n\n"
        f"It expires in {ttl_minutes} minutes. If you didn't request this, ignore this email."
    )
    body_html = (
        f"<p>Your Trianz Concierge verification code is:</p>"
        f"<p style='font-size:28px;font-weight:700;letter-spacing:4px'>{code}</p>"
        f"<p>It expires in {ttl_minutes} minutes. "
        f"If you didn't request this, you can ignore this email.</p>"
    )
    try:
        client = _ses_client(region)
        resp = client.send_email(
            FromEmailAddress=sender,
            Destination={"ToAddresses": [to_address]},
            Content={"Simple": {
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {
                    "Text": {"Data": body_text, "Charset": "UTF-8"},
                    "Html": {"Data": body_html, "Charset": "UTF-8"},
                },
            }},
        )
        logger.info("[SES] otp_sent  to=%s message_id=%s", to_address, resp.get("MessageId"))
        return {"sent": True, "message_id": resp.get("MessageId")}
    except Exception as exc:  # pragma: no cover - depends on live AWS
        logger.error("[SES] otp_send_failed  to=%s error=%s", to_address, exc)
        return {"sent": False, "error": str(exc)}


# ── meeting invite (.ics) ─────────────────────────────────────────────────────

def build_ics(
    *,
    summary: str,
    description: str,
    start: datetime,
    end: datetime,
    organizer_email: str,
    attendee_email: str,
    location: str = "Online",
) -> str:
    """Build a minimal RFC-5545 VEVENT as a string (no external dependency)."""
    def _fmt(dt: datetime) -> str:
        return dt.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")

    uid = f"{uuid.uuid4().hex}@trianz-concierge"
    desc = description.replace("\n", "\\n")
    return "\r\n".join([
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//Trianz//Concierge//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:REQUEST",
        "BEGIN:VEVENT",
        f"UID:{uid}",
        f"DTSTAMP:{_fmt(datetime.now(timezone.utc))}",
        f"DTSTART:{_fmt(start)}",
        f"DTEND:{_fmt(end)}",
        f"SUMMARY:{summary}",
        f"DESCRIPTION:{desc}",
        f"LOCATION:{location}",
        f"ORGANIZER:mailto:{organizer_email}",
        f"ATTENDEE;RSVP=TRUE:mailto:{attendee_email}",
        "STATUS:CONFIRMED",
        "SEQUENCE:0",
        "END:VEVENT",
        "END:VCALENDAR",
    ])


def send_meeting_email(
    *,
    to_address: str,
    subject: str,
    body_text: str,
    ics_text: str,
    ics_filename: str = "trianz-meeting.ics",
) -> dict:
    """Send a meeting invite with a .ics attachment via SES (raw MIME). Returns {sent, ...}."""
    sender, region = _ses_settings()
    if not sender:
        return {"sent": False, "error": "no_ses_sender_configured"}

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = to_address

    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(body_text, "plain", "utf-8"))
    msg.attach(alt)

    # Inline calendar part (so clients show Accept/Decline) ...
    cal_part = MIMEText(ics_text, "calendar", "utf-8")
    cal_part.add_header("Content-Class", "urn:content-classes:calendarmessage")
    cal_part.replace_header("Content-Type", 'text/calendar; method=REQUEST; charset="UTF-8"')
    msg.attach(cal_part)

    # ... and as a downloadable attachment.
    attach = MIMEApplication(ics_text.encode("utf-8"), _subtype="ics")
    attach.add_header("Content-Disposition", "attachment", filename=ics_filename)
    msg.attach(attach)

    try:
        client = _ses_client(region)
        resp = client.send_email(
            FromEmailAddress=sender,
            Destination={"ToAddresses": [to_address]},
            Content={"Raw": {"Data": msg.as_string().encode("utf-8")}},
        )
        logger.info("[SES] meeting_sent  to=%s message_id=%s", to_address, resp.get("MessageId"))
        return {"sent": True, "message_id": resp.get("MessageId")}
    except Exception as exc:  # pragma: no cover - depends on live AWS
        logger.error("[SES] meeting_send_failed  to=%s error=%s", to_address, exc)
        return {"sent": False, "error": str(exc)}
